
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ssl_user
      POSTGRES_PASSWORD: ssl_user123
      POSTGRES_DB: ssl_checker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db_data:
  pgadmin_data:
