"""Initial migration

Revision ID: 8d0ba4d5b8c6
Revises: 
Create Date: 2025-05-02 10:39:43.923768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0ba4d5b8c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'websites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websites', type_='foreignkey')
    op.drop_column('websites', 'user_id')
    # ### end Alembic commands ###
